language: node_js
node_js:
  - 18

if: tag =~ /^release\//

jobs:
  include:
    - stage: Build
      name: NPM Package
      script:
        - yarn install
        - yarn build
    - stage: Deploy
      script: yarn build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_AUTH_TOKEN'
        skip_cleanup: true
