language: node_js
node_js:
  - 17

if: tag =~ /^release\//

jobs:
  include:
    - stage: Build and Deploy
      script: 
      - yarn install
      - yarn build
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_AUTH_TOKEN'
        skip_cleanup: true
        on:
          all_branches: true
