language: node_js
node_js:
  - "19.x"

if: tag =~ /^release\//

jobs:
  include:
    - stage: Build
      name: NPM Package
      script:
        - yarn install
        - yarn build
    - stage: Deploy
      script: yarn build
      deploy:
        provider: NPM
        email: '$NPM_EMAIL'
        api_key: '$NPM_AUTH_TOKEN'
        skip_cleanup: true
